# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  # Traefik
  - 01-traefik/rbac.yaml
  - 01-traefik/ingressclass.yaml
  - 01-traefik/deployment.yaml
  - 01-traefik/service.yaml
  
  # Ingress principal
  - 02-ingress/main-ingress.yaml
  
  # Secrets & ConfigMaps
  - 03-secrets/db-credentials-configmap.yaml
  - 03-secrets/github-registry-secret.yaml  # ← Commenter si créé manuellement
  
  # Redis
  - 04-redis/deployment.yaml
  - 04-redis/service.yaml
  
  # Tyk Gateway
  - 05-tyk/configmap-gateway.yaml
  - 05-tyk/configmap-api-auth.yaml
  - 05-tyk/deployment.yaml
  - 05-tyk/service.yaml
  
  # Frontends
  - 06-frontends/back-office/deployment.yaml
  - 06-frontends/back-office/service.yaml
  
  # Microservices
  - 07-microservices/auth-api/deployment.yaml
  - 07-microservices/auth-api/service.yaml
  
  # Messaging
  - 08-messaging/rabbitmq/deployment.yaml
  - 08-messaging/rabbitmq/service.yaml