apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: preprod
spec:
  type: NodePort 
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: dashboard  
    port: 8080
    targetPort: 8080