---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBXFW5hxICFtWaUIHUoajee1hOHA8F8APysJT8cq21miRH2CiaHdpUECi7Ox826F9iIHVxN7Dvt/Mgydu+mAKRLtRH4n7hgGqr8+7BiKoLHoPbG7Cpwo93XjZTVATEFUhr3J/1rUYEnzRkAc0AAq7+7kAq9jHTRfIbyd4Gqjt8N0Ba+PEwQFVlwGtjDGNXH2FXxVyOMjwwly7nnE7JfoYx/OCbbiO0gDHvkIzf+aiM8sXHTH+uEmFUlegoWIFf0s5eJD7CJVTTVbIVH5sksopqk8rrNZJdhm5J1xv1IGTbv1S+layhjEexbhbsTeIUFxvgISzUoc/Kl9eraa4OYoz665IwPMYgRVQOI3hK2lDxq0ZFTaxUmfPKr34NDKyR4gPMHAspKvgC9YQ5NqCmjevpU7tYGQlGbzG5ygvAM/MpV45NDK+kFSgQlHtYSmyF/XAZVNv+Ft6H+BPuHH+lAvcheaJH8biuQ3v1a12zLVrPSx28weWx40egFCEGFQZGj6GPV7frDAtwIcEV1DWnStbQBTFToxqRwRKqCmCCo41hgKzOgsh4f4cUfWaUWqMnj1HsAxosMgawkh3BKe5F5GWJO7mO3D9MkWmXVjCsWC1X8JdPBOv0Q1EXFejdbkRzmVAPdghHREeRA/M1XMqzOOhiCQRKLIYKbGYHXpmGkR45MgnNAyqZ/zT1nuecwl9LFMb8Y8VWdkCkCOBsH0D259OgvzLZfqyqRjQNHmQkbCN5Z7dznFV1BQi7zlZYdNJr8zIhSCsfdBIotkxtPkk7R9svYrOMNDwSSNq+Q43FWxqLEKqQttdpcgbPhFPJir2Q9yWAY/LQZ/mYD2aShGicjJIPq1FKPTWgZPUNi0hcqqJlZ73Ugg3P7lFsYw5typUP0zM85SdUHtOk5yhZvqO1unTLnvjtoJh6bk+oKSPBC5NpiR5dmfG39QT8F0Tjoz9B6qw==
  template:
    metadata:
      name: ghcr-secret
    type: kubernetes.io/dockerconfigjson
