apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-api-definition
  namespace: default
data:
  auth-api.json: |
    {
      "name": "Auth API",
      "api_id": "auth-api",
      "org_id": "default",
      "use_keyless": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default"
          }
        }
      },
      "proxy": {
        "listen_path": "/auth/",
        "target_url": "http://authentification-api.preprod.svc.cluster.local:3000",
        "strip_listen_path": true
      }
    }