apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-api-definition
  namespace: default
data:
  authentification-api.json: |
    {
      "name": "Authentification API",
      "api_id": "authentification-api",
      "org_id": "default",
      "use_keyless": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default"
          }
        }
      },
      "proxy": {
        "listen_path": "/auth/",
        "target_url": "http://authentification-api:80",
        "strip_listen_path": true
      }
    }
  
  shop-api.json: |
    {
      "name": "Shop API",
      "api_id": "shop-api",
      "org_id": "default",
      "use_keyless": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default"
          }
        }
      },
      "proxy": {
        "listen_path": "/shop/",
        "target_url": "http://shop-api:80",
        "strip_listen_path": true
      }
    }
  
  order-api.json: |
    {
      "name": "Order API",
      "api_id": "order-api",
      "org_id": "default",
      "use_keyless": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default"
          }
        }
      },
      "proxy": {
        "listen_path": "/order/",
        "target_url": "http://order-api:80",
        "strip_listen_path": true
      }
    }
    
  order-api-ws.json: |
    {
      "name": "Order API WebSocket",
      "api_id": "order-api-ws",
      "org_id": "default",
      "use_keyless": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default"
          }
        }
      },
      "proxy": {
        "listen_path": "/order/ws/",
        "target_url": "http://order-api:8080",
        "strip_listen_path": true
      }
    }