# 05-tyk/configmap-api-auth.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-api-auth
  namespace: preprod
data:
  auth-api.json: |
    {
      "name": "Auth API",
      "api_id": "auth-api",
      "org_id": "default",
      "use_keyless": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default"
          }
        }
      },
      "proxy": {
        "listen_path": "/api/auth/",
        "target_url": "http://auth-api",
        "strip_listen_path": true
      }
    }